<?php

/**
 * Database XAPI class, handles Inserting/Removing database objects.
 *
 * @package zpanelx
 * @subpackage dryden -> db
 * @version 1.0.0
 * @author ballen (ballen@zpanelcp.com)
 */

class db_xapi {

    /**
     * Builds new cron file from databsae
     * @author RusTus (rustus@zpanelcp.com)
     * @version 10.0.0
     */
	static function cronjob_commit() {
	global $zdbh;

        //$sql = $zdbh->prepare("UPDATE x_settings SET so_value_tx = ? WHERE so_name_vc = ?");
		//$sql->execute(array('C', 'windows_drive'));
		
		$sql = $zdbh->prepare( "SELECT * FROM x_cronjobs");
		$sql->execute();
		fs_filehandler::ResetFile(ctrl_options::GetOption('cron_file'));
		
		while($row = $sql->fetch()) {
			$new_file  = "#################################################################################".fs_filehandler::NewLine();
			$new_file .= "# CRONTAB FOR ZPANEL CRON MANAGER MODULE                                        #".fs_filehandler::NewLine();
			$new_file .= "# Module Developed by Bobby Allen, 17/12/2009                                   #".fs_filehandler::NewLine();
			$new_file .= "# Automatically generated by ZPanel ".ctrl_options::GetOption('zpanel_version')." ".date('M-d-Y h:m:s').fs_filehandler::NewLine();
			$new_file .= "#################################################################################".fs_filehandler::NewLine();
			$new_file .= "# WE DO NOT RECOMMEND YOU MODIFY THIS FILE DIRECTLY, PLEASE USE ZPANEL INSTEAD! #".fs_filehandler::NewLine();
			$new_file .= "#################################################################################".fs_filehandler::NewLine();
			$new_file .= "# Cron Debug infomation can be found in this file here:-                        #".fs_filehandler::NewLine();
			$new_file .= "# WINDOWS:- C:\WINDOWS\System32\crontab.txt                                     #".fs_filehandler::NewLine();
			$new_file .= "# LINUX:- /var/log/syslog                                                       #".fs_filehandler::NewLine();
			$new_file .= "#################################################################################".fs_filehandler::NewLine();
			$new_file .= "0 * * * * ".ctrl_options::GetOption('php_exer')." ".ctrl_options::GetOption('zpanel_root')."daemon.php".fs_filehandler::NewLine();
			$new_file .= "#################################################################################".fs_filehandler::NewLine();
			$new_file .= "# DO NOT MANUALLY REMOVE ANY OF THE CRON ENTRIES FROM THIS FILE, USE ZPANEL     #".fs_filehandler::NewLine();
			$new_file .= "# INSTEAD! THE ABOVE ENTRIES ARE USED FOR ZPANEL TASKS, DO NOT REMOVE THEM!     #".fs_filehandler::NewLine();
			$new_file .= "#################################################################################".fs_filehandler::NewLine();
			$new_file .= "# CRON ID:" . $row['ct_id_pk'] . fs_filehandler::NewLine();
			$new_file .= "1 2 ".$row['ct_script_vc'].fs_filehandler::NewLine();
			$new_file .= "# END CRON ID:" . $row['ct_id_pk'] . fs_filehandler::NewLine();
			$fp = fopen(ctrl_options::GetOption('cron_file'),'a');
			fwrite($fp, $new_file);
			fclose($fp);
		}
	}

    /**
     * Builds new Apache Vhosts file from databsae
     * @author RusTus (rustus@zpanelcp.com)
     * @version 10.0.0
     */
	static function vhosts_commit() {
	global $zdbh;

		$sql = $zdbh->prepare( "SELECT * FROM x_vhosts" );
		$sql->execute();
		fs_filehandler::ResetFile(ctrl_options::GetOption('apache_vhosts'));
		
		$new_file  = "################################################################".fs_filehandler::NewLine();;
		$new_file .= "# Apache VHOST configuration file".fs_filehandler::NewLine();
		$new_file .= "# Automatically generated by ZPanel ".ctrl_options::GetOption('zpanel_version')." ".date('M-d-Y h:m:s').fs_filehandler::NewLine();
		$new_file .= "################################################################".fs_filehandler::NewLine();
		$new_file .= fs_filehandler::NewLine();		
		$new_file .= "NameVirtualHost *:".ctrl_options::GetOption('apache_port'). fs_filehandler::NewLine();
		$new_file .= fs_filehandler::NewLine();
		$new_file .= "#Configuration for ZPanel control panel.".fs_filehandler::NewLine();
		$new_file .= "<VirtualHost *:".ctrl_options::GetOption('apache_port').">".fs_filehandler::NewLine();
		$new_file .= "ServerAdmin zadmin@ztest.com".fs_filehandler::NewLine();
    	$new_file .= "DocumentRoot \"".ctrl_options::GetOption('zpanel_root')."\"".fs_filehandler::NewLine();
    	$new_file .= "ServerName zpanel.ztest.com".fs_filehandler::NewLine();
    	$new_file .= "ServerAlias *.zpanel.ztest.com".fs_filehandler::NewLine();
		$new_file .= "AddType application/x-httpd-php .php".fs_filehandler::NewLine();
		$new_file .= "<Directory \"".ctrl_options::GetOption('zpanel_root')."\">".fs_filehandler::NewLine();
		$new_file .= "Options FollowSymLinks".fs_filehandler::NewLine();
    	$new_file .= "AllowOverride All".fs_filehandler::NewLine();
    	$new_file .= "Order allow,deny".fs_filehandler::NewLine();
    	$new_file .= "Allow from all".fs_filehandler::NewLine();
		$new_file .= "</Directory>".fs_filehandler::NewLine();
		$new_file .= "</VirtualHost>".fs_filehandler::NewLine();
		$new_file .= fs_filehandler::NewLine();
		$new_file .= "################################################################".fs_filehandler::NewLine();
		$new_file .= "# ZPanel generated VHOST configurations below.....".fs_filehandler::NewLine();
		$new_file .= "################################################################".fs_filehandler::NewLine();
		$new_file .= fs_filehandler::NewLine();
		$fp = fopen(ctrl_options::GetOption('apache_vhosts'),'a');
		fwrite($fp, $new_file);
		fclose($fp);
		
		while($row = $sql->fetch()) {
			$new_file  = "# DOMAIN: ".$row['vh_name_vc'].fs_filehandler::NewLine();
			$new_file .= "<virtualhost *:".ctrl_options::GetOption('apache_port').">".fs_filehandler::NewLine();
			$new_file .= "ServerName ".$row['vh_name_vc']."\r\n";
			$new_file .= "ServerAlias ".$row['vh_name_vc']." www.".$row['vh_name_vc'].fs_filehandler::NewLine();
			$new_file .= "ServerAdmin ".$admin_email.fs_filehandler::NewLine();
			$new_file .= "DocumentRoot \"".$row['vh_directory_vc']."\"".fs_filehandler::NewLine();
			$new_file .= "php_admin_value open_basedir \"".ctrl_options::GetOption('hosted_dir').":".ctrl_options::GetOption('temp_dir')."\"".fs_filehandler::NewLine();
			$new_file .= "php_admin_value upload_tmp_dir \"".ctrl_options::GetOption('temp_dir')."\"".fs_filehandler::NewLine();
			$new_file .= "ErrorLog \"".ctrl_options::GetOption('logfile_dir').$row['vh_name_vc']."-error.log\"".fs_filehandler::NewLine();
			$new_file .= "CustomLog \"".ctrl_options::GetOption('logfile_dir').$row['vh_name_vc']."-access.log\" common".fs_filehandler::NewLine();
			$new_file .= "CustomLog \"".ctrl_options::GetOption('logfile_dir').$row['vh_name_vc']."-bandwidth.log\" common".fs_filehandler::NewLine();
			$new_file .= "<Directory />".fs_filehandler::NewLine();
			$new_file .= "Options FollowSymLinks Indexes".fs_filehandler::NewLine();
			$new_file .= "AllowOverride All".fs_filehandler::NewLine();
			$new_file .= "Order Allow,Deny".fs_filehandler::NewLine();
			$new_file .= "Allow from all".fs_filehandler::NewLine();
			$new_file .= "</Directory>".fs_filehandler::NewLine();
			$new_file .= ctrl_options::GetOption('php_handler').fs_filehandler::NewLine();
			$new_file .= "ScriptAlias /cgi-bin/ \"".$row['vh_name_vc']."/_cgi-bin/\"".fs_filehandler::NewLine();
			$new_file .= "<location /cgi-bin>".fs_filehandler::NewLine();
			$new_file .= ctrl_options::GetOption('cgi_handler').fs_filehandler::NewLine();
			$new_file .= "Options ExecCGI -Indexes".fs_filehandler::NewLine();
			$new_file .= "</location>".fs_filehandler::NewLine();
			$new_file .= ctrl_options::GetOption('error_pages').fs_filehandler::NewLine();
			//$new_file .= "$extra".fs_filehandler::NewLine(); #TO ADD CUSTOM ENRIES HERE
			$new_file .= "".ctrl_options::GetOption('directory_index').fs_filehandler::NewLine();
			$new_file .= "</virtualhost>".fs_filehandler::NewLine();
			$new_file .= "# END DOMAIN:".$row['vh_name_vc'].fs_filehandler::NewLine();
			$fp = fopen(ctrl_options::GetOption('apache_vhosts'),'a');
			fwrite($fp, $new_file);
			fclose($fp);
		}
	}

    /**
     * Builds new FTP file from databsae
     * @author RusTus (rustus@zpanelcp.com)
     * @version 10.0.0
     */
	 static function ftp_commit(){
	 	$sql = $zdbh->prepare( "SELECT * FROM x_vhosts" );
		$sql->execute();
		fs_filehandler::ResetFile(ctrl_options::GetOption('ftp'));
		
	 	if (ShowServerPlatform() == "Windows") {
		
		
		}else{
		
		}
	 
	 }
}

?>