language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6

script: for i in `find . -name "*.php"`; do php -l $i; done;

branches:
  only:
    - "master"
    - "stable"

notifications:
  email: false
