<?php

/*
 +-----------------------------------------------------------------------+
 | localization/bg_BG/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas <Unknown>                                              |
 +-----------------------------------------------------------------------+
 @version $Id: bg_BG.inc 5741 2012-01-08 16:20:12Z thomasb $
*/

$labels = array();
$labels['identitydialogtitle'] = 'Моля попълнете Вашите данни.';
$labels['identitydialoghint'] = 'Това съобщение се появява само при първото влизане.';

