<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ru_RU/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas <Unknown>                                              |
 +-----------------------------------------------------------------------+
 @version $Id: ru_RU.inc 5741 2012-01-08 16:20:12Z thomasb $
*/

$labels = array();
$labels['identitydialogtitle'] = 'Пожалуйста, укажите Ваше имя.';
$labels['identitydialoghint'] = 'Данное сообщение отображается только при первом входе.';

